server:
  port: 8083

spring:
  application:
    name: ms-citas-medicas

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/db_citas_medicas?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

springdoc:
  api-docs:
    enabled: true
    path: /api/citas-medicas/v3/api-docs